name: Build and Test Azure Function

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore serverless_stripe.sln
      - name: Build
        run: dotnet build serverless_stripe.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test tests/unit_test/UnitTests.csproj --configuration Release --no-build --verbosity normal
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Fetch Stripe API Key from Key Vault
        id: get-stripe-key
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.AZURE_KEYVAULT_NAME }}
          secrets: STRIPE_API_KEY
      - name: Set Stripe API Key as env
        run: echo "STRIPE_API_KEY=${{ steps.get-stripe-key.outputs.STRIPE_API_KEY }}" >> $GITHUB_ENV
